// Public frontend configuration only.
// MarocVows production community backend exists, but personal-data collection
// stays gated until operator/privacy contact, CNDP formalities, and Auth redirect
// configuration are complete. NEVER expose a service_role or secret key here.
window.CATERER_APP_CONFIG = {
  supabaseUrl: "",
  publishableKey: "",
  communityFeaturesEnabled: false
};

(()=>{
  const copy={
    en:{cats:['Catering','Venues','Photo & video','Décor & flowers','Neggafa','Music & DJ'],live:'Live now',next:'Next',about:'About',privacy:'Privacy',terms:'Terms',community:'Community Guidelines',contact:'Contact',privacyNote:'Current pilot: no advertising or behavioural-tracking cookies.',share:'Share your experience',shareSoon:'Community reviews are being prepared carefully. Browsing is live now; sign-in and contributions will open after the final privacy and authentication checks.',builderTitle:'What stood out?',builderHelp:'Tap any that fit. You can add a short note too — no long review needed.',noteLabel:'Anything else? (optional)',notePlaceholder:'A quick detail that would help the next family…',chips:['Great food','Professional staff','On time','Good communication','Good value','Beautiful presentation','Could improve communication','Could improve timing'],builtPrefix:'My experience:',thirty:'About 30 seconds · genuine experiences only'},
    ar:{cats:['التموين','القاعات','التصوير والفيديو','الديكور والورود','النكافة','الموسيقى وDJ'],live:'متاح الآن',next:'قريباً',about:'من نحن',privacy:'الخصوصية',terms:'الشروط',community:'قواعد المجتمع',contact:'التواصل',privacyNote:'النسخة الحالية: لا نستخدم ملفات إعلانية أو تتبع سلوكي.',share:'شارك تجربتك',shareSoon:'نعمل على إطلاق التقييمات بعناية. التصفح متاح الآن، وسيتم فتح تسجيل الدخول والمساهمات بعد استكمال فحوص الخصوصية والمصادقة.',builderTitle:'ما الذي أعجبك أو لفت انتباهك؟',builderHelp:'اختر ما يناسب تجربتك، ويمكنك إضافة ملاحظة قصيرة فقط.',noteLabel:'هل تريد إضافة شيء آخر؟ (اختياري)',notePlaceholder:'تفصيل صغير قد يساعد العائلة التالية…',chips:['طعام ممتاز','طاقم محترف','التزام بالوقت','تواصل جيد','سعر مناسب','تقديم جميل','التواصل يحتاج تحسيناً','الوقت يحتاج تحسيناً'],builtPrefix:'تجربتي:',thirty:'حوالي 30 ثانية · للتجارب الحقيقية فقط'},
    fr:{cats:['Traiteurs','Salles','Photo & vidéo','Décoration & fleurs','Neggafa','Musique & DJ'],live:'En ligne',next:'À venir',about:'À propos',privacy:'Confidentialité',terms:'Conditions',community:'Règles de la communauté',contact:'Contact',privacyNote:'Pilote actuel : aucun cookie publicitaire ni suivi comportemental.',share:'Partager votre expérience',shareSoon:'Les avis communautaires sont préparés avec soin. La consultation est en ligne ; les comptes et contributions ouvriront après les derniers contrôles de confidentialité et d’authentification.',builderTitle:'Qu’est-ce qui vous a marqué ?',builderHelp:'Touchez les éléments qui correspondent. Une courte note suffit — pas besoin d’écrire un long avis.',noteLabel:'Autre chose ? (facultatif)',notePlaceholder:'Un petit détail utile pour la prochaine famille…',chips:['Très bon repas','Équipe professionnelle','Ponctuel','Bonne communication','Bon rapport qualité-prix','Belle présentation','Communication à améliorer','Ponctualité à améliorer'],builtPrefix:'Mon expérience :',thirty:'Environ 30 secondes · expériences réelles uniquement'},
    es:{cats:['Catering','Salones','Foto y vídeo','Decoración y flores','Neggafa','Música y DJ'],live:'Activo',next:'Próximamente',about:'Sobre nosotros',privacy:'Privacidad',terms:'Términos',community:'Normas de la comunidad',contact:'Contacto',privacyNote:'Piloto actual: sin cookies publicitarias ni seguimiento conductual.',share:'Compartir tu experiencia',shareSoon:'Estamos preparando las opiniones comunitarias con cuidado. La navegación ya está activa; las cuentas y contribuciones se abrirán tras las últimas comprobaciones de privacidad y autenticación.',builderTitle:'¿Qué destacó?',builderHelp:'Toca lo que encaje con tu experiencia. También puedes añadir una nota corta; no hace falta escribir mucho.',noteLabel:'¿Algo más? (opcional)',notePlaceholder:'Un pequeño detalle que ayudaría a la próxima familia…',chips:['Comida excelente','Equipo profesional','Puntual','Buena comunicación','Buena relación calidad-precio','Presentación bonita','Comunicación mejorable','Puntualidad mejorable'],builtPrefix:'Mi experiencia:',thirty:'Unos 30 segundos · solo experiencias reales'}
  };
  const cfg=window.CATERER_APP_CONFIG||{};
  function lang(){const l=document.documentElement.lang||localStorage.getItem('mec-lang')||'en';return copy[l]?l:'en'}
  function meta(sel,value){const el=document.querySelector(sel);if(el&&value)el.setAttribute('content',value)}
  function brandify(){
    document.title='MarocVows | Wedding Caterers in Khénifra, Fès & Meknès';
    meta('meta[name="description"]','MarocVows helps couples and families discover wedding caterers in Morocco, compare local options, contact providers directly and read genuine community feedback.');
    meta('meta[property="og:title"]','MarocVows — Find trusted local wedding services in Morocco');
    meta('meta[property="og:description"]','A multilingual Morocco wedding guide built around local discovery, genuine community experiences and direct provider contact.');
    const brand=document.querySelector('.brand');if(brand){brand.setAttribute('aria-label','MarocVows home');const label=brand.querySelector('span:last-child');if(label)label.textContent='MarocVows'}
    const foot=document.querySelector('footer>p:first-child');if(foot)foot.textContent='© 2026 MarocVows';
    document.querySelectorAll('script[type="application/ld+json"]').forEach(s=>{try{const j=JSON.parse(s.textContent);if(j['@type']==='WebSite'){j.name='MarocVows';j.description='Multilingual wedding discovery guide for Morocco, starting with caterers in Khénifra, Fès and Meknès.';s.textContent=JSON.stringify(j)}}catch{}});
    if(!document.querySelector('link[rel="icon"]')){const icon=document.createElement('link');icon.rel='icon';icon.href='favicon.svg';icon.type='image/svg+xml';document.head.appendChild(icon)}
  }
  function ensureLegalFooter(){const footer=document.querySelector('footer');if(!footer||footer.querySelector('.footer-legal-nav'))return;const nav=document.createElement('nav');nav.className='footer-legal-nav';nav.setAttribute('aria-label','Legal');nav.innerHTML='<a href="about.html"></a><a href="privacy.html"></a><a href="terms.html"></a><a href="community-guidelines.html"></a><a href="contact.html"></a>';const note=document.createElement('p');note.className='footer-privacy-note';footer.append(nav,note)}
  function ensureStyles(){if(document.getElementById('marocvowsPolish'))return;const style=document.createElement('style');style.id='marocvowsPolish';style.textContent=`
  .footer-legal-nav{display:flex;flex-wrap:wrap;gap:8px 16px}.footer-legal-nav a{font-weight:750;text-decoration:underline;text-underline-offset:3px}.footer-privacy-note{max-width:430px}
  .experience-builder{margin:18px 0;padding:18px;border:1px solid var(--line);border-radius:16px;background:#fbf6ed}.experience-builder h3{margin:0 0 4px;font:600 1.15rem Georgia,serif}.experience-builder>p{margin:0 0 13px;color:var(--muted);font-size:.88rem}.experience-chips{display:flex;flex-wrap:wrap;gap:8px}.experience-chip{border:1px solid rgba(73,55,35,.18);background:white;color:var(--ink);border-radius:999px;padding:8px 11px;font-size:.82rem;font-weight:800;cursor:pointer}.experience-chip.is-selected{background:var(--forest);border-color:var(--forest);color:white}.experience-time{display:block;margin-top:11px;color:var(--muted);font-size:.76rem;font-weight:750}.community-soon{margin:14px 0;padding:14px 16px;border-radius:14px;background:#f4ead7;border:1px solid #e5cf9f;color:#5d4828;font-size:.88rem}.account-btn[disabled],.contribute-btn[disabled]{opacity:.58;cursor:not-allowed;transform:none!important}
  @media(max-width:700px){.footer-legal-nav{order:3;width:100%}.footer-privacy-note{order:4}.experience-builder{padding:15px}}
  `;document.head.appendChild(style)}
  function buildReviewExperience(){const form=document.getElementById('reviewForm'),text=document.getElementById('reviewText');if(!form||!text||document.querySelector('.experience-builder'))return;const box=document.createElement('div');box.className='experience-builder';box.innerHTML='<h3></h3><p></p><div class="experience-chips"></div><span class="experience-time"></span>';text.closest('label')?.before(box);const label=text.closest('label')?.querySelector('[data-i18n="reviewLabel"]');if(label)label.dataset.marocvowsNote='1';text.placeholder='';box.addEventListener('click',e=>{const b=e.target.closest('.experience-chip');if(!b)return;b.classList.toggle('is-selected');syncGeneratedReview()});text.addEventListener('input',()=>{if(!text.dataset.autogenerated)text.dataset.manual='1'});translateReviewBuilder()}
  function syncGeneratedReview(){const text=document.getElementById('reviewText');if(!text||text.dataset.manual==='1')return;const selected=[...document.querySelectorAll('.experience-chip.is-selected')].map(b=>b.textContent);if(!selected.length){if(text.dataset.autogenerated==='1')text.value='';delete text.dataset.autogenerated;return}const c=copy[lang()];text.value=`${c.builtPrefix} ${selected.join(' · ')}.`;text.dataset.autogenerated='1'}
  function translateReviewBuilder(){const c=copy[lang()],box=document.querySelector('.experience-builder');if(!box)return;box.querySelector('h3').textContent=c.builderTitle;box.querySelector('p').textContent=c.builderHelp;box.querySelector('.experience-time').textContent=c.thirty;const wrap=box.querySelector('.experience-chips');const selected=[...wrap.querySelectorAll('.experience-chip.is-selected')].map(b=>Number(b.dataset.index));wrap.innerHTML=c.chips.map((x,i)=>`<button type="button" class="experience-chip${selected.includes(i)?' is-selected':''}" data-index="${i}">${x}</button>`).join('');const label=document.querySelector('[data-marocvows-note]');if(label)label.textContent=c.noteLabel;const text=document.getElementById('reviewText');if(text)text.placeholder=c.notePlaceholder;const opts=document.querySelectorAll('#rating option');if(opts.length>=6){const rating={en:['—','5 — Excellent','4 — Very good','3 — Good','2 — Fair','1 — Poor'],ar:['—','5 — ممتاز','4 — جيد جداً','3 — جيد','2 — مقبول','1 — ضعيف'],fr:['—','5 — Excellent','4 — Très bien','3 — Bien','2 — Moyen','1 — Faible'],es:['—','5 — Excelente','4 — Muy bien','3 — Bien','2 — Regular','1 — Malo']}[lang()];opts.forEach((o,i)=>{if(rating[i])o.textContent=rating[i]})}syncGeneratedReview()}
  function gateCommunity(){if(cfg.communityFeaturesEnabled)return;const c=copy[lang()];const acc=document.getElementById('accountButton');if(acc){acc.disabled=true;acc.textContent=c.share;acc.title=c.shareSoon}document.querySelectorAll('.contribute-btn').forEach(b=>{b.disabled=true;b.textContent=c.share;b.title=c.shareSoon});const gate=document.getElementById('reviewAuthGate');if(gate){gate.innerHTML=`<p>${c.shareSoon}</p>`;gate.classList.add('community-soon')}const status=document.getElementById('reviewStatus');if(status)status.textContent=''}
  function translate(){const c=copy[lang()];const tiles=[...document.querySelectorAll('.category-tile')];tiles.forEach((tile,i)=>{const strong=tile.querySelector('strong'),small=tile.querySelector('small');if(strong&&c.cats[i])strong.textContent=c.cats[i];if(small)small.textContent=tile.classList.contains('is-live')?c.live:c.next});ensureLegalFooter();const nav=document.querySelector('.footer-legal-nav');if(nav){const links=[...nav.querySelectorAll('a')],labels=[c.about,c.privacy,c.terms,c.community,c.contact];links.forEach((a,i)=>a.textContent=labels[i])}const note=document.querySelector('.footer-privacy-note');if(note)note.textContent=c.privacyNote;translateReviewBuilder();gateCommunity()}
  function start(){brandify();ensureStyles();buildReviewExperience();translate();setTimeout(()=>{buildReviewExperience();translate();gateCommunity()},0);new MutationObserver(m=>{if(m.some(x=>x.attributeName==='lang'))translate()}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();