-- Morocco Wedding Guide community schema
-- Reviews, photos and reports require an authenticated account.
-- Public visitors can read approved content only.

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  vendor_slug text not null check (char_length(vendor_slug) between 2 and 100),
  user_id uuid not null references auth.users(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  reviewer_name text not null default 'Member' check (char_length(reviewer_name) between 1 and 80),
  review_text text not null check (char_length(review_text) between 20 and 800),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  unique (vendor_slug, user_id)
);

create index if not exists reviews_vendor_status_created_idx
  on public.reviews (vendor_slug, status, created_at desc);

alter table public.reviews enable row level security;
revoke all on table public.reviews from anon, authenticated;
grant select on table public.reviews to anon, authenticated;
grant insert on table public.reviews to authenticated;
grant usage, select on sequence public.reviews_id_seq to authenticated;

drop policy if exists "public can read approved reviews" on public.reviews;
create policy "public can read approved reviews"
on public.reviews for select
to anon, authenticated
using (status = 'approved');

drop policy if exists "members submit own pending reviews" on public.reviews;
create policy "members submit own pending reviews"
on public.reviews for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  and status = 'pending'
  and rating between 1 and 5
  and char_length(vendor_slug) between 2 and 100
  and char_length(reviewer_name) between 1 and 80
  and char_length(review_text) between 20 and 800
);

-- Moderated photo metadata.
create table if not exists public.vendor_photos (
  id bigint generated by default as identity primary key,
  vendor_slug text not null check (char_length(vendor_slug) between 2 and 100),
  uploader_id uuid not null references auth.users(id) on delete cascade,
  storage_path text not null unique check (char_length(storage_path) between 5 and 500),
  caption text check (caption is null or char_length(caption) <= 180),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now()
);

create index if not exists vendor_photos_vendor_status_idx
  on public.vendor_photos (vendor_slug, status, created_at desc);

alter table public.vendor_photos enable row level security;
revoke all on table public.vendor_photos from anon, authenticated;
grant select on table public.vendor_photos to anon, authenticated;
grant insert on table public.vendor_photos to authenticated;
grant usage, select on sequence public.vendor_photos_id_seq to authenticated;

drop policy if exists "public can read approved photos" on public.vendor_photos;
create policy "public can read approved photos"
on public.vendor_photos for select
to anon, authenticated
using (status = 'approved');

drop policy if exists "members submit own pending photos" on public.vendor_photos;
create policy "members submit own pending photos"
on public.vendor_photos for insert
to authenticated
with check (
  (select auth.uid()) = uploader_id
  and status = 'pending'
  and char_length(vendor_slug) between 2 and 100
);

-- Reports are private moderation data. Browser users can submit but cannot read them.
create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  vendor_slug text not null check (char_length(vendor_slug) between 2 and 100),
  reporter_id uuid not null references auth.users(id) on delete cascade,
  reason text not null check (reason in ('incorrect_details','closed','duplicate','inappropriate','other')),
  details text check (details is null or char_length(details) <= 600),
  status text not null default 'open' check (status in ('open','reviewing','resolved','dismissed')),
  created_at timestamptz not null default now()
);

create index if not exists reports_status_created_idx
  on public.reports (status, created_at desc);

alter table public.reports enable row level security;
revoke all on table public.reports from anon, authenticated;
grant insert on table public.reports to authenticated;
grant usage, select on sequence public.reports_id_seq to authenticated;

drop policy if exists "members submit own reports" on public.reports;
create policy "members submit own reports"
on public.reports for insert
to authenticated
with check (
  (select auth.uid()) = reporter_id
  and status = 'open'
);

-- Private storage bucket. Approved photos can be read through RLS and signed URLs.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'vendor-photos',
  'vendor-photos',
  false,
  8388608,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Uploads must live under /<user-id>/<vendor-slug>/<file>.
drop policy if exists "members upload own vendor photos" on storage.objects;
create policy "members upload own vendor photos"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'vendor-photos'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

-- Approved photo objects are readable by guests and members.
drop policy if exists "public reads approved vendor photos" on storage.objects;
create policy "public reads approved vendor photos"
on storage.objects for select
to anon, authenticated
using (
  bucket_id = 'vendor-photos'
  and exists (
    select 1
    from public.vendor_photos vp
    where vp.storage_path = storage.objects.name
      and vp.status = 'approved'
  )
);

-- Allow a member to clean up their own pending upload if metadata insertion fails.
drop policy if exists "members delete own pending uploads" on storage.objects;
create policy "members delete own pending uploads"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'vendor-photos'
  and (storage.foldername(name))[1] = (select auth.uid())::text
  and not exists (
    select 1
    from public.vendor_photos vp
    where vp.storage_path = storage.objects.name
      and vp.status = 'approved'
  )
);

-- No browser UPDATE or DELETE grants are provided for community tables.
-- Moderation should happen in the Supabase dashboard or trusted server-side tooling.
