-- Morocco Event Caterers: moderated public reviews
-- Run in the dedicated Supabase project for this site.

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  vendor_slug text not null check (char_length(vendor_slug) between 2 and 100),
  rating smallint not null check (rating between 1 and 5),
  reviewer_name text not null default 'Guest' check (char_length(reviewer_name) between 1 and 80),
  review_text text not null check (char_length(review_text) between 20 and 800),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now()
);

create index if not exists reviews_vendor_status_created_idx
  on public.reviews (vendor_slug, status, created_at desc);

alter table public.reviews enable row level security;

revoke all on table public.reviews from anon, authenticated;
grant select, insert on table public.reviews to anon, authenticated;
grant usage, select on sequence public.reviews_id_seq to anon, authenticated;

-- Visitors may read only approved reviews.
drop policy if exists "public can read approved reviews" on public.reviews;
create policy "public can read approved reviews"
on public.reviews for select
to anon, authenticated
using (status = 'approved');

-- Visitors may submit only pending reviews. They cannot self-approve them.
drop policy if exists "public can submit pending reviews" on public.reviews;
create policy "public can submit pending reviews"
on public.reviews for insert
to anon, authenticated
with check (
  status = 'pending'
  and rating between 1 and 5
  and char_length(vendor_slug) between 2 and 100
  and char_length(reviewer_name) between 1 and 80
  and char_length(review_text) between 20 and 800
);

-- No UPDATE or DELETE grants are given to browser roles.
-- Moderation should be done from the Supabase dashboard or trusted server-side tooling.
